# /etc/nginx/conf.d/phase-backends.conf
server {
    listen 127.0.0.1:8081;
    server_name _;
    root /var/www/phase1;
    index index.html;
    add_header X-Backend "phase1" always;
}

server {
    listen 127.0.0.1:8082;
    server_name _;
    root /var/www/phase2;
    index index.html;
    add_header X-Backend "phase2" always;
}

server {
    listen 127.0.0.1:8083;
    server_name _;
    root /var/www/phase3;
    index index.html;
    add_header X-Backend "phase3" always;
}
